#:schema https://secretspec.dev/schema/secretspec.schema.json
[project]
name = "nvim-config"
revision = "1.0"

[providers]
local = "dotenv"

[profiles.default]
KULALA_CORE_LICENSE_TOKEN = { description = "License token for downloading kulala-core prebuilt binaries", required = true, providers = ["local"] }
